apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: example
spec:
  parameters:
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKoZQbAbTmEQmFzsRwY1Qc9WEY3EPuryShqu1whWYCDt tobias.kasser@upbound.io"
    amiId: "ami-02a95d1e0bb2ad5ce"
    zone: a
