apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: example
spec:
  parameters:
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKoZQbAbTmEQmFzsRwY1Qc9WEY3EPuryShqu1whWYCDt tobias.kasser@upbound.io"
    amiId: "ami-06bc36b2df9129f2e"
    zone: a
    additionalPublicKeys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMXbvrMf29K2T/ubkmMlA4ER5NxJ+GlTqAkjF5rX/Mv yury@upbound.io"
