apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: upboxsets.aws.platform.upbound.io
spec:
  compositeTypeRef:
    apiVersion: aws.platform.upbound.io/v1alpha1
    kind: UpboxSet
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-configuration-upboxupboxset
    step: upboxset
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
