apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: upboxes.aws.platform.upbound.io
spec:
  compositeTypeRef:
    apiVersion: aws.platform.upbound.io/v1alpha1
    kind: Upbox
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-configuration-upboxupbox
    step: upbox
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
