apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: upbox-nike-edgard-castro-2
  annotations:
    render.crossplane.io/composition-path: apis/upbox/composition.yaml
    render.crossplane.io/function-path: examples/functions.yaml
    render.crossplane.io/definition-path: apis/upbox/definition.yaml
spec:
  # To connect from the AWS Console to the instance, see
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-prerequisites.html
  parameters:
    # email: Edgard.Vasconcellosdecastro@nike.com
    name: edgard-castro-2
    company: nike
    owner: team-nike-platform
    networkId: upbox-aws-network
    amiId: ami-0eab2975347a21ff0 # upbox-2025-3-23-v2
    size: medium
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDPPnjJrm0lsdelQifFC7lbRk8g/au4gdFKHDHcMV0NESuYO4wp0eVInQNQZIpC7onNZVK8nWJc9gggrThS1dNSI5W7J6xTwOZVYkvVicjjSpw9QG3czdBnU1Ywg52bFXbW7PoR79mpTKfMH8uY06jLZZUoFRO0E3misQUQCit/4UM3+YJHDFwvgySSb88HRduVFNslUwGCKzIFl4Ogbk9qNkmcT1o6Je+DLf+PmnbFxWur3NWuu9yLqPmyBbD2pdoCvKfaHtkilUUxw3Jeamq20emHt8o7z+QPCjrrk/Z5Qi3XUsglwTzMkz9AuuLMXPI1eKmgaj5wMyZvONg53w1P40LcrqBW1GbAa28+DIT6ucmb92bgzh9lJM4C55ONKqFaaA6UR1DY/jAq/zDR/w8tIfbyl4iTuJSRMnHEprhZBSB2gmwvT1ZShktUIEp0leWoU1SQgMdol0d13MaynmQxGsTUq8IhI84QFfWw7XuFgd8cd5SKi85Qb3l4TGq6zX8= markuss@Markuss-MacBook-Pro.local
    # publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5wGvLo5V4+osChU1n86j9Tm1/rotL+397M7AWvQTc1TPUi7yQQbXitPiTkz9WZUsfGDx38liwh6PWXZ4I4E++4S15sDNy4Wy4cGBPw3JRsv3l2WKILo/hDa3rN8+YqFD7wqBc1kyh946kbnO7A/BFn38/ijSGeJe6tt1EAqwlLCyhTg+zytJIBuzAWDyqaIGCGsqngtdZsb99roqJfA60O7K+ohVJ2kIFcqirjXSFd2f7vH8pMZ5Awzx75jClwPHgpxI4aESlcFLTM0W6yqwS7HqSUUTMgWREnsazTo8nmunHNVA8LiYdavhzTWrEAaNH6MJux7iG52ZoPId6ClRCUAujJOSLdkAft7ZaxstAuX+0Oh5a+MVx/TXk/G/KVl6KVSI3FkwlRGARm8I3v4/HkH7R4cFGtOos7hVeBtvk9bKqnoT4pY/bSKQSEAVRCdxsvJpkoLS/oG0MfkfdUPkvNhLotAaLXbKbj3BUPJKyBEAJXbGiIqSVuQ5lqbX197E= evasco@APQ92WV56F1E17
